import express from 'express';

// instantiate the server
const app = express();
app.use(express.json());
app.use(express.urlencoded({ extended: false }));

app.post('/submit-data', (req, res) => {
  res.send('Received a POST request from ' + req.body.name);
});

needle.post(
  'http://localhost:3000/add-book',
  { book: 'Harry Potter and the Philosopher’s Stone' },   // can be an object or a string
  (err, res) => {
    console.log(res.body);
  }
);

needle.post(
  'http://localhost:3000/add-isbn',
  { isbn: '978-0-7475-3269-9' },   // can be an object or a string
  (err, res) => {
    console.log(res.body);
  }
);

needle.post(
  'http://localhost:3000/submit-author',
  { author: 'J.K Rowling' },   // can be an object or a string
  (err, res) => {
    console.log(res.body);
  }
);

needle.post(
  'http://localhost:3000/submit-year',
  { year: '1997' },   // can be an object or a string
  (err, res) => {
    console.log(res.body);
  }
);



// this tells our app to listen for GET messages on the '/' path
// the callback function specifies what the server will do when a message is received
// app.get('/', (req, res) => {
//   res.send('Hello!');
// });

// // this tells our server to listen to the port 3000
// // we can also pass an optional callback function to execute after the server starts
// app.listen(3000, () => { console.log('Server started at port 3000')} );




// app.post('/submit-data', (req, res) => {
//   res.send('Received a POST request from ' + req.body.name);
// });

// app.post('/submit-data', (req, res) => {
//   res.send('Received a POST request.');
// });

// app.get('/', (req, res) => {
//   console.log(req);
//   console.log(res);  // this will show the default response object generated by Express. We can modify or add to this object before calling res.send()
//   res.send('Hello!');
// });

// app.get('/greeting', (req, res) => {
//    res.send('Hello ' + req.query.name);
// });


// app.use(express.json());
// app.use(express.urlencoded({ extended: false }));

// app.post('/submit-data', (req, res) => {
//   res.send('Received a POST request from ' + req.body.name);
// });


